const Forkpython = [
  {
    name: "Start Coding ",
    link: "https://practice.geeksforgeeks.org/problems/start-coding-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Start%20Coding%20-%20Python",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Space Seperated ",
    link: "https://practice.geeksforgeeks.org/problems/space-seperated-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Space%20Seperated%20-%20Python",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "sep and end in Print()",
    link: "https://practice.geeksforgeeks.org/problems/sep-and-end-in-print/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/sep%20and%20end%20in%20Print()",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Repetitive Printing",
    link: "https://practice.geeksforgeeks.org/problems/repeatitive-printing-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Repetitive%20Printing",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Concatenating Strings",
    link: "https://practice.geeksforgeeks.org/problems/concatenating-strings-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Concatenating%20Strings",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Taking input and typecasting",
    link: "https://practice.geeksforgeeks.org/problems/taking-input-and-typecasting-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Taking%20input%20and%20typecasting",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Taking input",
    link: "https://practice.geeksforgeeks.org/problems/taking-input-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Taking%20input",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Split the input",
    link: "https://practice.geeksforgeeks.org/problems/split-the-input-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Split%20the%20input",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Comment in Python",
    link: "https://practice.geeksforgeeks.org/problems/comment-in-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Comment%20in%20Python",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Operators in Python",
    link: "https://practice.geeksforgeeks.org/problems/operators-in-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Operators%20in%20Python",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Comparison Operators",
    link: "https://practice.geeksforgeeks.org/problems/comparison-operators-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Comparison%20Operators",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Logical Operators",
    link: "https://practice.geeksforgeeks.org/problems/logical-operators-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Logical%20Operators",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Increment and Decrement",
    link: "https://practice.geeksforgeeks.org/problems/increment-and-decrement-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Increment%20and%20Decrement",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Bitwise Operators",
    link: "https://practice.geeksforgeeks.org/problems/bitwise-operators-python/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Bitwise%20Operators",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Is and In Operator",
    link: "https://practice.geeksforgeeks.org/problems/is-and-in-operator/1/?track=fork-python&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%201/Is%20and%20In%20Operator",
    video: "",
    level: "Easy",
    topic: "Basics",
  },

  {
    name: "If conditional statement",
    link: "https://practice.geeksforgeeks.org/problems/if-loop-python/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/If%20conditional%20statement",
    video: "",
    level: "Easy",
    topic: "Control Structure",
  },
  {
    name: "Mark Even and Odd",
    link: "https://practice.geeksforgeeks.org/problems/mark-even-and-odd/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/Mark%20Even%20and%20Odd",
    video: "",
    level: "Easy",
    topic: "Control Structure",
  },
  {
    name: "Check the status",
    link: "https://practice.geeksforgeeks.org/problems/check-the-status/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/Check%20the%20status",
    video: "",
    level: "Easy",
    topic: "Control Structure",
  },
  {
    name: "For loop - Python",
    link: "https://practice.geeksforgeeks.org/problems/for-loop-python/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/For%20loop%20-%20Python",
    video: "",
    level: "Easy",
    topic: "Control Structure",
  },
  {
    name: "While loop in Python",
    link: "https://practice.geeksforgeeks.org/problems/while-loop-in-python/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/While%20loop%20in%20Python",
    video: "",
    level: "Easy",
    topic: "Control Structure",
  },
  {
    name: "Jumping through While",
    link: "https://practice.geeksforgeeks.org/problems/jumping-through-while-python/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/Jumping%20through%20While",
    video: "",
    level: "Easy",
    topic: "Control Structure",
  },
  {
    name: "Zero Converter",
    link: "https://practice.geeksforgeeks.org/problems/zero-converter-python/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/Zero%20Converter",
    video: "",
    level: "Medium",
    topic: "Control Structure",
  },
  {
    name: "Cat and Hat",
    link: "https://practice.geeksforgeeks.org/problems/cat-and-hat-python/1/?track=python-module-2&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%202/Cat%20and%20Hat",
    video: "",
    level: "Medium",
    topic: "Control Structure",
  },
  {
    name: "Welcome aboard",
    link: "https://practice.geeksforgeeks.org/problems/welcome-aboard-python/1/?track=python-module-3&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%203/Welcome%20aboard",
    video: "",
    level: "Easy",
    topic: "Strings",
  },
  {
    name: "Slicing in String",
    link: "https://practice.geeksforgeeks.org/problems/slicing-in-string-python/1/?track=python-module-3&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%203/Slicing%20in%20String",
    video: "",
    level: "Easy",
    topic: "Strings",
  },
  {
    name: "Repeat the Strings",
    link: "https://practice.geeksforgeeks.org/problems/repeat-the-strings/1/?track=python-module-3&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%203/Repeat%20the%20Strings",
    video: "",
    level: "Easy",
    topic: "Strings",
  },
  {
    name: "String Functions I",
    link: "https://practice.geeksforgeeks.org/problems/string-functions-i/1/?track=python-module-3&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%203/String%20Functions%20I",
    video: "",
    level: "Easy",
    topic: "Strings",
  },
  {
    name: "String Functions - II",
    link: "https://practice.geeksforgeeks.org/problems/string-functions-ii/1/?track=python-module-3&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%203/String%20Functions%20-%20II",
    video: "",
    level: "Easy",
    topic: "Strings",
  },
  {
    name: "Regular Expressions 2",
    link: "https://practice.geeksforgeeks.org/problems/regular-expressions-2-python/1/?track=python-module-3&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%203/Regular%20Expressions%202",
    video: "",
    level: "Easy",
    topic: "Strings",
  },
  {
    name: "Functions",
    link: "https://practice.geeksforgeeks.org/problems/functions-python/1/?track=python-module-4&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%204/Functions",
    video: "",
    level: "Easy",
    topic: "Classes & Function",
  },
  {
    name: "Classes and Objects",
    link: "https://practice.geeksforgeeks.org/problems/classes-and-objects-python/1/?track=python-module-4&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%204/Classes%20and%20Objects",
    video: "",
    level: "Easy",
    topic: "Classes & Function",
  },
  {
    name: "Variable Arguments",
    link: "https://practice.geeksforgeeks.org/problems/variable-arguments-python/1/?track=python-module-4&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%204/Variable%20Arguments",
    video: "",
    level: "Easy",
    topic: "Classes & Function",
  },
  {
    name: "Anonymous Functions",
    link: "https://practice.geeksforgeeks.org/problems/anonymous-functions-python/1/?track=python-module-4&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%204/Anonymous%20Functions",
    video: "",
    level: "Easy",
    topic: "Classes & Function",
  },
  {
    name: "Modules",
    link: "https://practice.geeksforgeeks.org/problems/modules/1/?track=python-module-4&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%204/Modules",
    video: "",
    level: "Easy",
    topic: "Classes & Function",
  },
  {
    name: "Intro to Lists",
    link: "https://practice.geeksforgeeks.org/problems/intro-to-lists-python/1/?track=python-module-5&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%205/Intro%20to%20Lists",
    video: "",
    level: "Easy",
    topic: "Lists",
  },
  {
    name: "Iterating through Lists",
    link: "https://practice.geeksforgeeks.org/problems/iterating-through-lists-python/1/?track=python-module-5&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%205/Iterating%20through%20Lists",
    video: "",
    level: "Easy",
    topic: "Lists",
  },
  {
    name: "Count Even Odd",
    link: "https://practice.geeksforgeeks.org/problems/count-even-odd-python/1/?track=python-module-5&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%205/Count%20Even%20Odd",
    video: "",
    level: "Easy",
    topic: "Lists",
  },
  {
    name: "Functions in Lists",
    link: "https://practice.geeksforgeeks.org/problems/functions-in-lists-python/1/?track=python-module-5&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%205/Functions%20in%20Lists",
    video: "",
    level: "Easy",
    topic: "Lists",
  },
  {
    name: "Average_Min_Max",
    link: "https://practice.geeksforgeeks.org/problems/average-min-max/1/?track=python-module-5&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%205/Average_Min_Max",
    video: "",
    level: "Easy",
    topic: "Lists",
  },
  {
    name: "Sorting in Lists",
    link: "https://practice.geeksforgeeks.org/problems/sorting-in-lists-python/1/?track=python-module-5&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%205/Sorting%20in%20Lists",
    video: "",
    level: "Easy",
    topic: "Lists",
  },
  {
    name: "Intro to Dictionary",
    link: "https://practice.geeksforgeeks.org/problems/intro-to-dictionary-python/1/?track=python-module-6&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%206/Intro%20to%20Dictionary",
    video: "",
    level: "Easy",
    topic: "Dictionary & Sets",
  },
  {
    name: "Dictionary in Python - II",
    link: "https://practice.geeksforgeeks.org/problems/dictionary-in-python-ii/1/?track=python-module-6&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%206/Dictionary%20in%20Python%20-%20II",
    video: "",
    level: "Easy",
    topic: "Dictionary & Sets",
  },
  {
    name: "Dictionary in Python - III ",
    link: "https://practice.geeksforgeeks.org/problems/dictionary-in-python-iii/1/?track=python-module-6&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%206/Dictionary%20in%20Python%20-%20III",
    video: "",
    level: "Easy",
    topic: "Dictionary & Sets",
  },
  {
    name: "Set in Python - I",
    link: "https://practice.geeksforgeeks.org/problems/set-in-python-i/1/?track=python-module-6&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%206/Set%20in%20Python%20-%20I",
    video: "",
    level: "Easy",
    topic: "Dictionary & Sets",
  },
  {
    name: "Set in Python - II",
    link: "https://practice.geeksforgeeks.org/problems/set-in-python-ii/1/?track=python-module-6&batchId=119",
    sol: "https://github.com/Soham-Official/Fork-Python/blob/main/Module%206/Set%20in%20Python%20-%20II",
    video: "",
    level: "Easy",
    topic: "Dictionary & Sets",
  },
  // {
  //   name: "",
  //   link: "",
  //   sol: "",
  //   video: "",
  //   level: "",
  //   topic: "",
  // },
  // {
  //   name: "",
  //   link: "",
  //   sol: "",
  //   video: "",
  //   level: "",
  //   topic: "",
  // },
];
export default Forkpython;
