const Forkjava = [
  {
    name: "Start Coding",
    link: "https://practice.geeksforgeeks.org/problems/start-coding-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Start%20Coding%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "The New Line",
    link: "https://practice.geeksforgeeks.org/problems/the-new-line-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/The%20New%20Line%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "Taking input",
    link: "https://practice.geeksforgeeks.org/problems/taking-input-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Taking%20input%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "nextLine and next",
    link: "https://practice.geeksforgeeks.org/problems/nextline-and-next/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/nextLine%20and%20next",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "Precise Fomat",
    link: "https://practice.geeksforgeeks.org/problems/precise-fomat-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Precise%20Fomat%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "logical Operators",
    link: "https://practice.geeksforgeeks.org/problems/logical-operators-java/1/?track=module-1-basics-and-control-structures-java&batchId=114#",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/logical%20Operators%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "Bitwise Operators",
    link: "https://practice.geeksforgeeks.org/problems/bitwise-operators-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Bitwise%20Operators%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Java",
  },
  {
    name: " Even Odd",
    link: " https://practice.geeksforgeeks.org/problems/even-odd-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Even%20Odd%20-%20Java",
    video: "",
    level: "Easy",
    topic: "condition flow",
  },

  {
    name: "Step by Step Condition",
    link: "https://practice.geeksforgeeks.org/problems/step-by-step-condition-java/1/?track=module-1-basics-and-control-structures-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Step%20by%20Step%20Condition%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Condition flow ",
  },
  {
    name: "Prime Check",
    link: "https://practice.geeksforgeeks.org/problems/for-loop-primecheck-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/For%20Loop-%20primeCheck%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Loop ",
  },
  {
    name: "Print table",
    link: "https://practice.geeksforgeeks.org/problems/while-loop-printtable-java/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/While%20loop-%20printTable%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Loop",
  },
  {
    name: "Java Hello World",
    link: "https://practice.geeksforgeeks.org/problems/java-hello-world4004/1/?track=module-1-basics-and-control-structures-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Java%20Hello%20World",
    level: "Easy",
    topic: "Java",
  },
  {
    name: "Count Odd Even",
    link: "https://practice.geeksforgeeks.org/problems/count-odd-even-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Count%20Odd%20Even%20-%20Java",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Need Some Change-Java",
    link: "https://practice.geeksforgeeks.org/problems/need-some-change-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Need%20Some%20Change%20-%20Java",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Count the Specials",
    link: "https://practice.geeksforgeeks.org/problems/count-the-specials-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Count%20the%20Specials%20-%20Java",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Matrix Interchange",
    link: "https://practice.geeksforgeeks.org/problems/matrix-interchange-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Matrix%20Interchange%20-%20Java",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Predict the Column",
    link: "https://practice.geeksforgeeks.org/problems/predict-the-column-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Predict%20the%20Column%20-%20Java",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Consonants and Vowel Check",
    link: "https://practice.geeksforgeeks.org/problems/consonants-and-vowels-check-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Consonants%20and%20Vowels%20check%20-%20Java",
    level: "Easy",
    topic: "String",
  },
  {
    name: "Almost Equal",
    link: "https://practice.geeksforgeeks.org/problems/almost-equal-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: "https://github.com/prarthita-blip/fork_java/blob/main/Almost%20Equal%20-Java",
    level: "Easy",
    topic: "String",
  },
  {
    name: "The Pattern Matcher",
    link: "https://practice.geeksforgeeks.org/problems/the-pattern-matcher-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/The%20Pattern%20Matcher",
    video: "",
    level: "Easy",
    topic: "String",
  },
  {
    name: "Xoring and Clearing",
    link: "https://practice.geeksforgeeks.org/problems/xoring-and-clearing-java/1/?track=module-2-arrays-and-strings-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Xoring%20and%20Clearing",
    video: "",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Even Subset",
    link: "https://practice.geeksforgeeks.org/problems/even-subsets-java/1/?track=module-2-arrays-and-strings-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Even%20Subsets",
    video: "",
    level: "Easy",
    topic: "Bits",
  },
  {
    name: "Need some Change",
    link: "https://practice.geeksforgeeks.org/problems/need-some-change/1/?track=module-2-arrays-and-strings-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Need%20Some%20Change",
    video: "",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Pair in java",
    link: "https://practice.geeksforgeeks.org/problems/pair-in-java/1/?track=module-3-classes%20and-biginteger-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Pair%20in%20Java",
    video: "",
    level: "Easy",
    topic: "Class",
  },
  {
    name: "Maximum Area in Rectangle ",
    link: "https://practice.geeksforgeeks.org/problems/maximum-area-rectangle/1/?track=module-3-classes%20and-biginteger-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Maximum%20Area%20Rectangle",
    video: "",
    level: "Easy",
    topic: "Class",
  },
  {
    name: "Sum of Big Integers ",
    link: "https://practice.geeksforgeeks.org/problems/sum-of-big-integers/1/?track=module-3-classes%20and-biginteger-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Sum%20of%20Big%20Integers",
    video: "",
    level: "Easy",
    topic: "BigInteger",
  },
  {
    name: "Big Integer Multiply ",
    link: "https://practice.geeksforgeeks.org/problems/biginteger-multiply/1/?track=module-3-classes%20and-biginteger-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/BigInteger%20Multiply",
    video: "",
    level: "Easy",
    topic: "BigInteger",
  },
  {
    name: "Big Integer Mod ",
    link: "https://practice.geeksforgeeks.org/problems/biginteger-mod/1/?track=module-3-classes%20and-biginteger-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/BigInteger%20mod",
    video: "",
    level: "Easy",
    topic: "BigInteger",
  },
  {
    name: "Stack Operations ",
    link: "https://practice.geeksforgeeks.org/problems/stacks-operations/1/?track=module-4-stacks-queues-and-lists-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Stack%20Operations",
    video: "",
    level: "Easy",
    topic: "Stack",
  },
  {
    name: "Queue Operations ",
    link: "https://practice.geeksforgeeks.org/problems/queue-operations/1/?track=module-4-stacks-queues-and-lists-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Queue%20Operations",
    video: "",
    level: "Easy",
    topic: "Queue",
  },
  {
    name: "Operations on Priority Queue ",
    link: "https://practice.geeksforgeeks.org/problems/operations-on-priorityqueue/1/?track=module-4-stacks-queues-and-lists-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Operations%20on%20PriorityQueue",
    video: "",
    level: "Medium",
    topic: "Queue",
  },
  {
    name: "ArrayList Operation ",
    link: "https://practice.geeksforgeeks.org/problems/arraylist-operation/1/?track=module-4-stacks-queues-and-lists-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/ArrayList%20Operation",
    video: "",
    level: "Easy",
    topic: "ArrayList",
  },
  {
    name: " Operations on ArrayList",
    link: "https://practice.geeksforgeeks.org/problems/operations-on-arraylist/1/?track=module-4-stacks-queues-and-lists-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Operations%20on%20ArrayList",
    video: "",
    level: "Easy",
    topic: "ArrayList",
  },
  {
    name: "Sum The Common Elements",
    link: "https://practice.geeksforgeeks.org/problems/sum-the-common-elements/1/?track=module-5-sets-and-map-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Sum%20the%20common%20elements",
    video: "",
    level: "Easy",
    topic: "HashSet",
  },
  {
    name: "Greater and Smaller Ones",
    link: "https://practice.geeksforgeeks.org/problems/greater-and-smaller-ones/1/?track=module-5-sets-and-map-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Greater%20and%20Smaller%20Ones",
    video: "",
    level: "Easy",
    topic: "HashSet",
  },
  {
    name: "Pair Sum Existence",
    link: "https://practice.geeksforgeeks.org/problems/pair-sum-existence/1/?track=module-5-sets-and-map-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Pair%20Sum%20Existence",
    video: "",
    level: "Easy",
    topic: "HashSet",
  },
  {
    name: "Parties and seats",
    link: "https://practice.geeksforgeeks.org/problems/parties-and-seats/1/?track=module-5-sets-and-map-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Parties%20and%20seats",
    video: "",
    level: "Easy",
    topic: "HashMap",
  },
  {
    name: "Duplicate Elements",
    link: "https://practice.geeksforgeeks.org/problems/duplicate-elements/1/?track=module-5-sets-and-map-java&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Duplicate%20Elements",
    video: "",
    level: "Easy",
    topic: "HashMap",
  },
  {
    name: "Frequency Game",
    link: "https://practice.geeksforgeeks.org/problems/frequency-game/1/?track=module-5-sets-and-map-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Frequency%20Game",
    video: "",
    level: "Easy",
    topic: "HashMap",
  },
  {
    name: "Pair Sum Existence-Revisited",
    link: "https://practice.geeksforgeeks.org/problems/pair-sum-existence-revisited/1/?track=module-5-sets-and-map-java&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Pair%20Sum%20Existence-Revisited",
    video: "",
    level: "Easy",
    topic: "HashMap",
  },
  {
    name: "Dictionary Usage",
    link: "https://practice.geeksforgeeks.org/problems/dictionary-usage-java/1/?track=module-6-misc-java%20&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Dictionary%20Usage%20-%20Java",
    video: "",
    level: "Easy",
    topic: "Dictionary",
  },
  {
    name: "Dictionary Usage 2",
    link: "https://practice.geeksforgeeks.org/problems/dictionary-usage-2-java/1/?track=module-6-misc-java%20&batchId=114#",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Dictionary%20Usage%202",
    video: "",
    level: "Easy",
    topic: "Dictionary",
  },
  {
    name: "Using Calendar",
    link: "https://practice.geeksforgeeks.org/problems/using-calendar-java/1/?track=module-6-misc-java%20&batchId=114",
    sol: " https://github.com/prarthita-blip/fork_java/blob/main/Using%20Calendar",
    video: "",
    level: "Easy",
    topic: "Calendar",
  },
];
export default Forkjava;
