const Forkcpp = [
  {
    name: "C++ Hello World",
    link: "https://practice.geeksforgeeks.org/problems/c-hello-world3402/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/C%2B%2B%20Hello%20World",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "The New Line",
    link: "https://practice.geeksforgeeks.org/problems/the-new-line/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/The%20New%20Line",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Data Types",
    link: "https://practice.geeksforgeeks.org/problems/data-types/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Data%20Types",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Taking input",
    link: "https://practice.geeksforgeeks.org/problems/taking-input/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Taking%20input",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Learn to Comment",
    link: "https://practice.geeksforgeeks.org/problems/learn-to-comment/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Learn%20to%20Comment",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "GetLine and Ignore",
    link: "https://practice.geeksforgeeks.org/problems/getline-and-ignore/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/GetLine%20and%20Ignore",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Learning to be precise",
    link: "https://practice.geeksforgeeks.org/problems/learning-to-be-precise/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Learning%20to%20be%20precise",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Learning Macros",
    link: "https://practice.geeksforgeeks.org/problems/learning-macros/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Learning%20Macros",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Start Coding",
    link: "https://practice.geeksforgeeks.org/problems/start-coding/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Start%20Coding",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "The Size of",
    link: "https://practice.geeksforgeeks.org/problems/the-size-of/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/The%20Size%20of",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Logical Operators",
    link: "https://practice.geeksforgeeks.org/problems/logical-operators/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Logical%20Operators",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Bitwise Operators",
    link: "https://practice.geeksforgeeks.org/problems/bitwise-operators/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Bitwise%20Operators",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Even Odd",
    link: "https://practice.geeksforgeeks.org/problems/even-odd/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Even%20Odd",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Step by Step Condition",
    link: "https://practice.geeksforgeeks.org/problems/step-by-step-condition/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/Step%20by%20Step%20Condition",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "For Loop- primeCheck",
    link: "https://practice.geeksforgeeks.org/problems/for-loop-primechecl/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/For%20Loop-%20primeCheck",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "While loop- printTable",
    link: "https://practice.geeksforgeeks.org/problems/while-loop-printtable/1/?track=module-1-basics-and-control-structures&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%201/While%20loop-%20printTable",
    video: "",
    level: "Easy",
    topic: "Basics",
  },
  {
    name: "Count Odd Even",
    link: "https://practice.geeksforgeeks.org/problems/count-odd-even/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Count%20Odd%20Even",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Need Some Change",
    link: "https://practice.geeksforgeeks.org/problems/need-some-change/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Need%20Some%20Change",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Count the Specials",
    link: "https://practice.geeksforgeeks.org/problems/count-the-specials/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Count%20the%20Specials",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Predict the Column",
    link: "https://practice.geeksforgeeks.org/problems/predict-the-column/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Predict%20the%20Column",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Xoring and Clearing",
    link: "https://practice.geeksforgeeks.org/problems/xoring-and-clearing/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Xoring%20and%20Clearing",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Even Subsets",
    link: "https://practice.geeksforgeeks.org/problems/even-subsets/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Even%20Subsets",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Consonants and Vowels check",
    link: "https://practice.geeksforgeeks.org/problems/consonants-and-vowels-check/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Consonants%20and%20Vowels%20check",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Almost Equal",
    link: "https://practice.geeksforgeeks.org/problems/almost-equal/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/Almost%20Equal",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "The Pattern Matcher",
    link: "https://practice.geeksforgeeks.org/problems/the-pattern-matcher/1/?track=module-2-arrays-and-strings&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%202/The%20Pattern%20Matcher",
    video: "",
    level: "Easy",
    topic: "Array & Strings",
  },
  {
    name: "Magic in CPP",
    link: "https://practice.geeksforgeeks.org/problems/magic-in-cpp/1/?track=module-3-pointers-and-objects%20&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%203/Magic%20in%20CPP",
    video: "",
    level: "Easy",
    topic: "Pointer & Objects",
  },
  {
    name: "Two Dimensional World",
    link: "https://practice.geeksforgeeks.org/problems/two-dimensional-world/1/?track=module-3-pointers-and-objects%20&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%203/Two%20Dimensional%20World",
    video: "",
    level: "Easy",
    topic: "Pointer & Objects",
  },
  {
    name: "Delete Array",
    link: "https://practice.geeksforgeeks.org/problems/delete-array/1/?track=module-3-pointers-and-objects%20&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%203/Delete%20Array",
    video: "",
    level: "Easy",
    topic: "Pointer & Objects",
  },
  {
    name: "Swap the objects",
    link: "https://practice.geeksforgeeks.org/problems/swap-the-objects/1/?track=module-3-pointers-and-objects%20&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%203/Swap%20the%20objects",
    video: "",
    level: "Easy",
    topic: "Pointer & Objects",
  },
  {
    name: "Structs and Objects",
    link: "https://practice.geeksforgeeks.org/problems/structs-and-objects/1/?track=module-3-pointers-and-objects%20&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%203/Structs%20and%20Objects",
    video: "",
    level: "Easy",
    topic: "Pointer & Objects",
  },
  {
    name: "Learning Structs",
    link: "https://practice.geeksforgeeks.org/problems/learning-structs/1/?track=module-3-pointers-and-objects%20&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%203/Learning%20Structs",
    video: "",
    level: "Easy",
    topic: "Pointer & Objects",
  },
  {
    name: "Sort and Reverse Vector",
    link: "https://practice.geeksforgeeks.org/problems/sort-and-reverse-vector/1/?track=module-4-vector-and-pair&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%204/Sort%20and%20Reverse%20Vector",
    video: "",
    level: "Easy",
    topic: "Vector & Pair",
  },
  {
    name: "Find the Frequency",
    link: "https://practice.geeksforgeeks.org/problems/find-the-frequency/1/?track=module-4-vector-and-pair&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%204/Find%20the%20Frequency",
    video: "",
    level: "Easy",
    topic: "Vector & Pair",
  },
  {
    name: "Front to Back",
    link: "https://practice.geeksforgeeks.org/problems/front-to-back/1/?track=module-4-vector-and-pair&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%204/Front%20to%20Back",
    video: "",
    level: "Easy",
    topic: "Vector & Pair",
  },
  {
    name: "Back to Front",
    link: "https://practice.geeksforgeeks.org/problems/back-to-front/1/?track=module-4-vector-and-pair&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%204/Back%20to%20Front",
    video: "",
    level: "Easy",
    topic: "Vector & Pair",
  },
  {
    name: "Pair Sum in Vector",
    link: "https://practice.geeksforgeeks.org/problems/pair-sum-in-vector/1/?track=module-4-vector-and-pair&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%204/Pair%20Sum%20in%20Vector",
    video: "",
    level: "Easy",
    topic: "Vector & Pair",
  },
  {
    name: "Student of the Year",
    link: "https://practice.geeksforgeeks.org/problems/student-of-the-year/1/?track=module-4-vector-and-pair&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%204/Student%20of%20the%20Year",
    video: "",
    level: "Easy",
    topic: "Vector & Pair",
  },
  {
    name: "Stack designer",
    link: "https://practice.geeksforgeeks.org/problems/stack-designer/1/?track=module-5-stacks-and-queues&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%205/Stack%20designer",
    video: "",
    level: "Easy",
    topic: "Stack & Queues",
  },
  {
    name: "Get min at pop",
    link: "https://practice.geeksforgeeks.org/problems/get-min-at-pop/1/?track=module-5-stacks-and-queues&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%205/Get%20min%20at%20pop",
    video: "",
    level: "Easy",
    topic: "Stack & Queues",
  },
  {
    name: "Queue Push & Pop",
    link: "https://practice.geeksforgeeks.org/problems/queue-designer/1/?track=module-5-stacks-and-queues&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%205/Queue%20Push%20%26%20Pop",
    video: "",
    level: "Easy",
    topic: "Stack & Queues",
  },
  {
    name: "Deque Implementations",
    link: "https://practice.geeksforgeeks.org/problems/deque-implementations/1/?track=module-5-stacks-and-queues&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%205/Deque%20Implementations",
    video: "",
    level: "Easy",
    topic: "Stack & Queues",
  },
  {
    name: "Min Heap implementation",
    link: "https://practice.geeksforgeeks.org/problems/min-heap-implementation/1/?track=module-5-stacks-and-queues&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%205/Min%20Heap%20implementation",
    video: "",
    level: "Easy",
    topic: "Stack & Queues",
  },
  {
    name: "Set Operations",
    link: "https://practice.geeksforgeeks.org/problems/set-operations/1/?track=module-6-sets-and-maps&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%206/Set%20Operations",
    video: "",
    level: "Easy",
    topic: "Set & Maps",
  },
  {
    name: "Multiset Operations",
    link: "https://practice.geeksforgeeks.org/problems/multiset-operations/1/?track=module-6-sets-and-maps&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%206/Multiset%20Operations",
    video: "",
    level: "Easy",
    topic: "Set & Maps",
  },
  {
    name: "Map Operations",
    link: "https://practice.geeksforgeeks.org/problems/map-operations/1/?track=module-6-sets-and-maps&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%206/Map%20Operations",
    video: "",
    level: "Easy",
    topic: "Set & Maps",
  },
  {
    name: "Multimap Operations",
    link: "https://practice.geeksforgeeks.org/problems/multimap-operations/1/?track=module-6-sets-and-maps&batchId=113",
    sol: "https://github.com/Soham-Official/Fork-cpp/blob/main/Module%206/Multimap%20Operations",
    video: "",
    level: "Easy",
    topic: "Set & Maps",
  },
  // {
  //   name: "",
  //   link: "",
  //   sol: "",
  //   video: "",
  //   level: "",
  //   topic: "",
  // },
  // {
  //   name: "",
  //   link: "",
  //   sol: "",
  //   video: "",
  //   level: "",
  //   topic: "",
  // },
  // {
  //   name: "",
  //   link: "",
  //   sol: "",
  //   video: "",
  //   level: "",
  //   topic: "",
  // },
];
export default Forkcpp;
