const Sdesheet = [
  {
    name: "Sort an array of 0’s 1’s 2’s",
    link: "https://leetcode.com/problems/sort-colors/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%201/Sort%20an%20array%20of%200%E2%80%99s%201%E2%80%99s%202%E2%80%99s",
    java: "",
    video:
      "https://www.youtube.com/watch?v=oaVa-9wmpns&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=2",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Repeat and Missing Number",
    link: "https://practice.geeksforgeeks.org/problems/find-missing-and-repeating2512/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%201/Repeat%20and%20Missing%20Number",
    java: "",
    video:
      "https://www.youtube.com/watch?v=5nMGY4VUoRY&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=3 ",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Merge two sorted Arrays",
    link: "https://practice.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%201/Merge%20two%20sorted%20Arrays%20without%20extra%20space",
    java: "",
    video:
      "https://www.youtube.com/watch?v=hVl2b3bLzBw&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=4  ",
    level: "Hard",
    topic: "Array",
  },
  {
    name: "Kadane’s Algorithm ",
    link: "https://leetcode.com/problems/maximum-subarray/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%201/Kadane%E2%80%99s%20Algorithm",
    java: "",
    video:
      "https://www.youtube.com/watch?v=w_KEocd__20&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=5 ",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Merge Overlapping Subintervals",
    link: "https://leetcode.com/problems/merge-intervals/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%201/Merge%20Intervals",
    java: "",
    video:
      "https://www.youtube.com/watch?v=2JzRBPFYbKE&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=6 ",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Find the duplicate",
    link: "https://leetcode.com/problems/find-the-duplicate-number/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%201/Find%20the%20Duplicate%20Number",
    java: "",
    video:
      "https://www.youtube.com/watch?v=32Ll35mhWg0&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=1",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Set Matrix Zeros",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%202/Set%20Matrix%20Zeroes",
    java: "",
    video:
      "https://www.youtube.com/watch?v=M65xBewcqcI&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=7",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Pascal Triangle",
    link: "https://leetcode.com/problems/pascals-triangle/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%202/Pascal%20Triangle",
    java: "",
    video:
      "https://www.youtube.com/watch?v=6FLvhQjZqvM&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=8 ",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Next Permutation",
    link: "https://leetcode.com/problems/next-permutation/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%202/Next%20Permutation",
    java: "",
    video:
      "https://www.youtube.com/watch?v=LuLCLgMElus&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=9",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Inversion of Array",
    link: "https://practice.geeksforgeeks.org/problems/inversion-of-array-1587115620/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%202/Inversion%20of%20Array",
    java: "",
    video:
      "https://www.youtube.com/watch?v=kQ1mJlwW-c0&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=10",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Stock Buy and Sell",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%202/Stock%20Buy%20and%20Sell",
    java: "",
    video:
      "https://www.youtube.com/watch?v=eMSfBgbiEjk&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=11",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Rotate Matrix",
    link: "https://leetcode.com/problems/rotate-image/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%202/Rotate%20Matrix",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Y72QeX0Efxw&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=12",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Search in a 2D matrix",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%203/Search%20a%202D%20Matrix",
    java: "",
    video:
      "https://www.youtube.com/watch?v=ZYpYur0znng&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=14",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Pow(X,n)",
    link: "https://leetcode.com/problems/powx-n/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%203/Pow(x%2C%20n)",
    java: "",
    video:
      "https://www.youtube.com/watch?v=l0YC3876qxg&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=15",
    level: "Medium",
    topic: "Math",
  },
  {
    name: "Majority Element (>N/2 times)",
    link: "https://leetcode.com/problems/majority-element/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%203/Majority%20Element",
    java: "",
    video:
      "https://www.youtube.com/watch?v=AoX3BPWNnoE&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=16",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Majority Element (>N/3 times)",
    link: "https://leetcode.com/problems/majority-element-ii/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%203/Majority%20Element%20II",
    java: "",
    video:
      "https://www.youtube.com/watch?v=yDbkQd9t2ig&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=17",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Grid Unique Paths",
    link: "https://leetcode.com/problems/unique-paths/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%203/Unique%20Paths",
    java: "",
    video:
      "https://www.youtube.com/watch?v=t_f0nwwdg5o&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=18",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Reverse Pairs",
    link: "https://leetcode.com/problems/reverse-pairs/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%203/Reverse%20Pairs",
    java: "",
    video:
      "https://www.youtube.com/watch?v=S6rsAlj_iB4&list=PLgUwDviBIf0rPG3Ictpu74YWBQ1CaBkm2&index=19",
    level: "Hard",
    topic: "Array",
  },
  {
    name: "2 Sum problem",
    link: "https://leetcode.com/problems/two-sum/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%204/Two%20Sum",
    java: "",
    video:
      "https://www.youtube.com/watch?v=dRUpbt8vHpo&list=PLgUwDviBIf0rVwua0kKYlsS_ik_1lyVK_&index=2",
    level: "Easy",
    topic: "Hashing",
  },
  {
    name: "4 Sum problem",
    link: "https://leetcode.com/problems/4sum/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%204/4Sum",
    java: "",
    video:
      "https://www.youtube.com/watch?v=4ggF3tXIAp0&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=21",
    level: "Medium",
    topic: "Hashing",
  },
  {
    name: "Longest Consecutive Sequence",
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%204/Longest%20Consecutive%20Sequence",
    java: "",
    video:
      "https://www.youtube.com/watch?v=qgizvmgeyUM&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=22",
    level: "Medium",
    topic: "Hashing",
  },
  {
    name: "Largest Subarray with 0 sum",
    link: "https://practice.geeksforgeeks.org/problems/largest-subarray-with-0-sum/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%204/Largest%20subarray%20with%200%20sum",
    java: "",
    video:
      "https://www.youtube.com/watch?v=xmguZ6GbatA&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=23",
    level: "Easy",
    topic: "Hashing",
  },
  {
    name: "Number of subarrays with given XOR",
    link: "https://www.geeksforgeeks.org/count-number-subarrays-given-xor/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%204/Count%20the%20number%20of%20subarrays%20having%20a%20given%20XOR",
    java: "",
    video:
      "https://www.youtube.com/watch?v=lO9R5CaGRPY&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=24",
    level: "Hard",
    topic: "Hashing",
  },
  {
    name: "Longest substring without repeat",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%204/Longest%20Substring%20Without%20Repeating%20Characters",
    java: "",
    video:
      "https://www.youtube.com/watch?v=qtVh-XEpsJo&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=26",
    level: "Medium",
    topic: "Hashing",
  },
  {
    name: "Reverse a LinkedList",
    link: "https://leetcode.com/problems/reverse-linked-list/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%205/Reverse%20Linked%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=iRtLEoL-r-g&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=27",
    level: "Easy",
    topic: "Linked List",
  },
  {
    name: "Find middle of LinkedList",
    link: "https://leetcode.com/problems/middle-of-the-linked-list/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%205/Middle%20of%20the%20Linked%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=sGdwSH8RK-o&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=28",
    level: "Easy",
    topic: "Linked List",
  },
  {
    name: "Merge two sorted Linked List",
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%205/Merge%20Two%20Sorted%20Lists",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Xb4slcp1U38&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=29",
    level: "Medium",
    topic: "Linked List",
  },
  {
    name: "Remove N-th node from back",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%205/Remove%20Nth%20Node%20From%20End%20of%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Lhu3MsXZy-Q&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=30",
    level: "Medium",
    topic: "Linked List",
  },
  {
    name: "Delete a given Node(0(1) solution) ",
    link: "https://leetcode.com/problems/delete-node-in-a-linked-list/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%205/Delete%20Node%20in%20a%20Linked%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=icnp4FJdZ_c&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=31",
    level: "Easy",
    topic: "Linked List",
  },
  {
    name: "Add two numbers as LinkedList",
    link: "https://leetcode.com/problems/add-two-numbers/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%205/Add%20Two%20Numbers",
    java: "",
    video:
      "https://www.youtube.com/watch?v=LBVsXSMOIk4&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=32",
    level: "Medium",
    topic: "Linked List",
  },
  {
    name: "Find intersection point LinkedList",
    link: "https://leetcode.com/problems/intersection-of-two-linked-lists/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%206/Intersection%20of%20Two%20Linked%20Lists",
    java: "",
    video:
      "https://www.youtube.com/watch?v=u4FWXfgS8jw&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=33",
    level: "Easy",
    topic: "Linked List",
  },
  {
    name: "Detect a cycle in Linked List",
    link: "https://leetcode.com/problems/linked-list-cycle/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%206/Linked%20List%20Cycle",
    java: "",
    video:
      "https://www.youtube.com/watch?v=354J83hX7RI&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=34",
    level: "Easy",
    topic: "Linked List",
  },
  {
    name: "Reverse a LinkedList in groups.",
    link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%206/Reverse%20Nodes%20in%20k-Group",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Of0HPkk3JgI&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=34",
    level: "Hard",
    topic: "Linked List",
  },
  {
    name: "Check if a LinkedList is palindrome.",
    link: "https://leetcode.com/problems/palindrome-linked-list/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%206/Palindrome%20Linked%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=-DtNInqFUXs&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=36",
    level: "Easy",
    topic: "Linked List",
  },
  {
    name: "Starting point of the Loop of LinkedList.",
    link: "https://leetcode.com/problems/linked-list-cycle-ii/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%206/Linked%20List%20Cycle%20II",
    java: "",
    video:
      "https://www.youtube.com/watch?v=QfbOhn0WZ88&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=37",
    level: "Medium",
    topic: "Linked List",
  },
  {
    name: "Flattening of a LinkedList",
    link: "https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%206/Flattening%20a%20Linked%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=ysytSSXpAI0&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=38",
    level: "Medium",
    topic: "Linked List",
  },
  {
    name: "Rotate a LinkedList",
    link: "https://leetcode.com/problems/rotate-list/description/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%207/Rotate%20List",
    java: "",
    video:
      "https://www.youtube.com/watch?v=9VPm6nEbVPA&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=39",
    level: "Medium",
    topic: "Linked List",
  },
  {
    name: "Clone a Linked List ",
    link: "https://leetcode.com/problems/copy-list-with-random-pointer/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%207/Copy%20List%20with%20Random%20Pointer",
    java: "",
    video:
      "https://www.youtube.com/watch?v=VNf6VynfpdM&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=40",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "3 sum",
    link: "https://leetcode.com/problems/3sum/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%207/3Sum",
    java: "",
    video:
      "https://www.youtube.com/watch?v=onLoX6Nhvmg&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=41",
    level: "Medium",
    topic: "Array",
  },
  {
    name: "Trapping rainwater",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%207/Trapping%20Rain%20Water",
    java: "",
    video:
      "https://www.youtube.com/watch?v=m18Hntz4go8&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=42",
    level: "Hard",
    topic: "Array",
  },
  {
    name: "Remove Duplicate from Sorted array",
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%207/Remove%20Duplicates%20from%20Sorted%20Array",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Fm_p9lJ4Z_8&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=43",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "Max consecutive ones.",
    link: "https://leetcode.com/problems/max-consecutive-ones/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%207/Max%20Consecutive%20Ones",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Mo33MjjMlyA&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=44",
    level: "Easy",
    topic: "Array",
  },
  {
    name: "N meeting in one room",
    link: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%208/N%20meetings%20in%20one%20room",
    java: "",
    video:
      "https://www.youtube.com/watch?v=dxVcMDI7vyI&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=45",
    level: "Medium",
    topic: "Greedy",
  },
  {
    name: "Minimum number of platforms required for a railway",
    link: "https://practice.geeksforgeeks.org/problems/minimum-platforms-1587115620/1#",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%208/Minimum%20Platforms",
    java: "",
    video:
      "https://www.youtube.com/watch?v=dxVcMDI7vyI&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=46",
    level: "Easy",
    topic: "Greedy",
  },
  {
    name: "Job sequencing Problem",
    link: "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1#",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%208/Job%20Sequencing%20Problem",
    java: "",
    video:
      "https://www.youtube.com/watch?v=LjPx4wQaRIs&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=47",
    level: "Medium",
    topic: "Greedy",
  },
  {
    name: "Fractional Knapsack Problem",
    link: "https://practice.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%208/Fractional%20Knapsack",
    java: "",
    video:
      "https://www.youtube.com/watch?v=F_DDzYnxO14&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=49",
    level: "Medium",
    topic: "Greedy",
  },
  {
    name: "Find minimum number of coins",
    link: "https://practice.geeksforgeeks.org/problems/-minimum-number-of-coins4426/1/?track=md-dp&batchId=144",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%208/Minimum%20number%20of%20Coins",
    java: "",
    video:
      "https://www.youtube.com/watch?v=mVg9CfJvayM&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=48",
    level: "Easy",
    topic: "Greedy",
  },
  {
    name: "Activity Selection",
    link: "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%208/N%20meetings%20in%20one%20room",
    java: "",
    video:
      "https://www.youtube.com/watch?v=II6ziNnub1Q&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=45",
    level: "Easy",
    topic: "Greedy",
  },
  {
    name: "Subset Sums",
    link: "https://practice.geeksforgeeks.org/problems/subset-sums2234/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%209/Subset%20Sums",
    java: "",
    video:
      "https://www.youtube.com/watch?v=rYkfBRtMJr8&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=53",
    level: "Basic",
    topic: "Recursion",
  },
  {
    name: "Subset-II",
    link: "https://leetcode.com/problems/subsets-ii/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%209/Subsets%20II",
    java: "",
    video:
      "https://www.youtube.com/watch?v=RIn3gOkbhQE&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=53",
    level: "Medium",
    topic: "Recursion",
  },
  {
    name: "Combination sum-1",
    link: "https://leetcode.com/problems/combination-sum/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%209/Combination%20Sum",
    java: "",
    video:
      "https://www.youtube.com/watch?v=OyZFFqQtu98&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=49",
    level: "Medium",
    topic: "Recursion",
  },
  {
    name: "Combination sum-2 ",
    link: "https://leetcode.com/problems/combination-sum-ii/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%209/Combination%20Sum%20II",
    java: "",
    video:
      "https://www.youtube.com/watch?v=G1fRTGRxXU8&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=50",
    level: "Medium",
    topic: "Recursion",
  },
  {
    name: "Palindrome Partitioning",
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%209/Palindrome%20Partitioning",
    java: "",
    video:
      "https://www.youtube.com/watch?v=WBgsABoClE0&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=51 ",
    level: "Medium",
    topic: "Recursion",
  },
  {
    name: "K-th permutation Sequence",
    link: "https://leetcode.com/problems/permutation-sequence/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%209/Permutation%20Sequence",
    java: "",
    video:
      "https://www.youtube.com/watch?v=wT7gcXLYoao&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=55 ",
    level: "Hard",
    topic: "Recursion",
  },
  {
    name: "Print all Permutations of a string/array",
    link: "https://leetcode.com/problems/permutations/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2010/Permutations",
    java: "",
    video:
      "https://www.youtube.com/watch?v=f2ic2Rsc9pU&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=52",
    level: "Medium",
    topic: "Backtracking",
  },
  {
    name: "N queens Problem ",
    link: "https://leetcode.com/problems/n-queens/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2010/N-Queens",
    java: "",
    video:
      "https://www.youtube.com/watch?v=i05Ju7AftcM&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=57",
    level: "Hard",
    topic: "Backtracking",
  },
  {
    name: "Sudoku Solver",
    link: "https://leetcode.com/problems/sudoku-solver/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2010/Sudoku%20Solver",
    java: "",
    video:
      "https://www.youtube.com/watch?v=FWAIf_EVUKE&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=58",
    level: "Hard",
    topic: "Backtracking",
  },
  {
    name: "M coloring Problem",
    link: "https://practice.geeksforgeeks.org/problems/m-coloring-problem-1587115620/1#",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2010/M-Coloring%20Problem",
    java: "",
    video:
      "https://www.youtube.com/watch?v=wuVwUK25Rfc&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=59",
    level: "Medium",
    topic: "Backtracking",
  },
  {
    name: "Rat in a Maze",
    link: "https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2010/Rat%20in%20a%20Maze%20Problem%20-%20I",
    java: "",
    video:
      "https://www.youtube.com/watch?v=bLGZhJlt4y0&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=60",
    level: "Medium",
    topic: "Backtracking",
  },
  {
    name: "N-th root of an integer",
    link: "",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/N-th%20root%20of%20an%20integer%20(use%20binary%20search)%20(square%20root%2C%20cube%20root%2C%20..)",
    java: "",
    video:
      "https://www.youtube.com/watch?v=WjpswYrS2nY&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=61 ",
    level: "",
    topic: "Binary Search",
  },
  {
    name: "Matrix Median",
    link: "https://www.interviewbit.com/problems/matrix-median/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/Matrix%20Median",
    java: "",
    video:
      "https://www.youtube.com/watch?v=63fPPOdIr2c&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=62",
    level: "Medium",
    topic: "Binary Search",
  },
  {
    name: "Single Element in Sorted Array",
    link: "https://leetcode.com/problems/single-element-in-a-sorted-array/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/Single%20Element%20in%20a%20Sorted%20Array",
    java: "",
    video:
      "https://www.youtube.com/watch?v=PzszoiY5XMQ&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=63",
    level: "Medium",
    topic: "Binary Search",
  },
  {
    name: "Search in Rotated Sorted Array",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/Search%20in%20Rotated%20Sorted%20Array",
    java: "",
    video:
      "https://www.youtube.com/watch?v=r3pMQ8-Ad5s&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=64",
    level: "Medium",
    topic: "Binary Search",
  },
  {
    name: "Median of 2 sorted arrays",
    link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/Median%20of%20Two%20Sorted%20Arrays",
    java: "",
    video:
      "https://www.youtube.com/watch?v=NTop3VTjmxk&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=65 ",
    level: "Hard",
    topic: "Binary Search",
  },
  {
    name: "K-th element of two sorted arrays",
    link: "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/K-th%20element%20of%20two%20sorted%20Arrays",
    java: "",
    video:
      "https://www.youtube.com/watch?v=nv7F4PiLUzo&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=66 ",
    level: "Medium",
    topic: "Binary Search",
  },
  {
    name: "Allocate Minimum Number of Pages",
    link: "https://www.interviewbit.com/problems/allocate-books/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/Allocate%20minimum%20number%20of%20pages",
    java: "",
    video:
      "https://www.youtube.com/watch?v=gYmWHvRHu-s&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=69 ",
    level: "Medium",
    topic: "Binary Search",
  },
  {
    name: "Aggressive Cows",
    link: "https://www.spoj.com/problems/AGGRCOW/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2011/Aggressive%20Cows",
    java: "",
    video:
      "https://www.youtube.com/watch?v=wSOfYesTBRk&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=70 ",
    level: "Medium",
    topic: "Binary Search",
  },
  {
    name: "Check if a number if a power of 2.",
    link: "https://practice.geeksforgeeks.org/problems/power-of-2-1587115620/1/?track=dsa-workshop-1-bit-magic&batchId=308",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2012/Power%20of%202",
    java: "",
    video: "",
    level: "Easy",
    topic: "Bits",
  },
  {
    name: "Count total set bits",
    link: "https://practice.geeksforgeeks.org/problems/count-total-set-bits-1587115620/0/?track=dsa-workshop-1-bit-magic&batchId=308",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2012/Count%20total%20set%20bits",
    java: "",
    video: "",
    level: "Medium",
    topic: "Bits",
  },
  {
    name: "Divide Integers without/operator",
    link: "https://leetcode.com/problems/divide-two-integers/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2012/Divide%20Two%20Integers",
    java: "",
    video: "",
    level: "Medium",
    topic: "Bits",
  },
  {
    name: "Power Set",
    link: "https://practice.geeksforgeeks.org/problems/power-set4302/1#",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2012/Power%20Set",
    java: "",
    video:
      "https://www.youtube.com/watch?v=b7AYbpM5YrE&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=67",
    level: "Easy",
    topic: "Bits",
  },
  {
    name: "Find MSB in o(1)",
    link: "https://www.geeksforgeeks.org/find-significant-set-bit-number/",
    sol: "https://www.geeksforgeeks.org/find-significant-set-bit-number/",
    java: "",
    video: "",
    level: "Easy",
    topic: "Bits",
  },
  {
    name: "Square of a number without using *,/ operators",
    link: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/",
    sol: "https://www.geeksforgeeks.org/calculate-square-of-a-number-without-using-and-pow/",
    java: "",
    video: "",
    level: "",
    topic: "Bits",
  },
  {
    name: "Implement Stack Using Arrays",
    link: "https://practice.geeksforgeeks.org/problems/implement-stack-using-array/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2013/Implement%20stack%20using%20array",
    java: "",
    video:
      "https://www.youtube.com/watch?v=GYptUgnIM_I&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=68",
    level: "Easy",
    topic: "Stack",
  },
  {
    name: "Implement Queue Using Arrays",
    link: "https://www.geeksforgeeks.org/array-implementation-of-queue-simple/",
    sol: "https://www.geeksforgeeks.org/array-implementation-of-queue-simple/",
    java: "",
    video:
      "https://www.youtube.com/watch?v=M6GnoUDpqEE&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=72",
    level: "",
    topic: "Queue",
  },
  {
    name: "Implement Stack using Queue",
    link: "https://leetcode.com/problems/implement-stack-using-queues/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2013/Implement%20Stack%20using%20Queues",
    java: "",
    video:
      "https://www.youtube.com/watch?v=jDZQKzEtbYQ&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=74",
    level: "Easy",
    topic: "Queue",
  },
  {
    name: "Implement Queue using Stack",
    link: "https://leetcode.com/problems/implement-queue-using-stacks/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2013/Implement%20Queue%20using%20Stacks",
    java: "",
    video:
      "https://www.youtube.com/watch?v=3Et9MrMc02A&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=75",
    level: "Easy",
    topic: "Stack",
  },
  {
    name: "Check for balanced parentheses",
    link: "https://leetcode.com/problems/valid-parentheses/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2013/Valid%20Parentheses",
    java: "",
    video:
      "https://www.youtube.com/watch?v=wkDfsKijrZ8&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=74",
    level: "",
    topic: "Stack",
  },
  {
    name: "Next Greater Element",
    link: "https://leetcode.com/problems/next-greater-element-ii/",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2013/Next%20Greater%20Element%20II",
    java: "",
    video:
      "https://www.youtube.com/watch?v=Du881K7Jtk8&list=PLgUwDviBIf0p4ozDR_kJJkONnb1wdx2Ma&index=75",
    level: "Medium",
    topic: "Stack",
  },
  {
    name: "Sort a Stack",
    link: "https://practice.geeksforgeeks.org/problems/sort-a-stack/1",
    sol: "https://github.com/Soham-Official/sdeSheet/blob/main/Day%2013/Sort%20a%20stack",
    java: "",
    video: "",
    level: "Easy",
    topic: "Stack",
  },
  // {
  //   name: "",
  //   link: "",
  //   sol: "",
  //   video: "",
  //   level: "",
  //   topic: "",
  // },
];
export default Sdesheet;
